// Contractor Licenses organized by category
// Data from docs/certifications-organized.md

export const LICENSE_CATEGORIES = {
  'General Licenses': [
    'Class A',
    'Class B',
    'Class B-2',
  ],
  'Specialty Contractors (Class C)': [
    'C-2',
    'C-4',
    'C-5',
    'C-6',
    'C-7',
    'C-8',
    'C-9',
    'C-10',
    'C-11',
    'C-12',
    'C-13',
    'C-15',
    'C-16',
    'C-17',
    'C-20',
    'C-21',
    'C-22',
    'C-29',
    'C-35',
    'C-36',
    'C-38',
    'C-39',
    'C-46',
    'C-47',
    'C-51',
    'C-53',
    'C-54',
    'C-55',
    'C-57',
    'C-60',
  ],
  'Limited Specialty (C-61)': [
    'D-49',
    'D-50',
    'D-52',
    'D-59',
    'D-62',
    'D-63',
  ],
} as const;

// Flat array of all licenses for dropdowns
export const ALL_LICENSES = Object.values(LICENSE_CATEGORIES).flat();

// Type for contractor license
export type ContractorLicense = typeof ALL_LICENSES[number];

// US States for license issuing state selection
export const US_STATES = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
  { value: 'DC', label: 'District of Columbia' },
] as const;
